version: '3.1'

services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariadb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
