version: '3.1'

services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
    ports:
      - ${DB_PORT}:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - ${WEB_PORT}:8080
